const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST'
const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
const CREATE_POST_FAILURE = 'CREATE_POST_FAILURE'

const SET_CURRENT_DATA_REQUEST = 'SET_CURRENT_DATA_REQUEST'
const SET_CURRENT_DATA_SUCCESS = 'SET_CURRENT_DATA_SUCCESS'
const SET_CURRENT_DATA_FAILURE = 'SET_CURRENT_DATA_FAILURE'

export { 
    CREATE_POST_REQUEST, 
    CREATE_POST_SUCCESS, 
    CREATE_POST_FAILURE,
    SET_CURRENT_DATA_FAILURE,
    SET_CURRENT_DATA_REQUEST,
    SET_CURRENT_DATA_SUCCESS
}
