const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST'
const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
const CREATE_POST_FAILURE = 'CREATE_POST_FAILURE' 

export { CREATE_POST_REQUEST, CREATE_POST_SUCCESS, CREATE_POST_FAILURE }
