const GET_POST_LIST_REQUEST = 'GET_POST_LIST_REQUEST'
const GET_POST_LIST_SUCCESS = 'GET_POST_LIST_SUCCESS'
const GET_POST_LIST_FAILURE = 'GET_POST_LIST_FAILURE'

const FETCH_DELETE_POST_REQUEST = 'FETCH_DELETE_POST_REQUEST'
const FETCH_DELETE_POST_SUCCESS = 'FETCH_DELETE_POST_SUCCESS'
const FETCH_DELETE_POST_FAILURE = 'FETCH_DELETE_POST_FAILURE'

const SET_CURRENT_DATA_REQUEST = 'SET_CURRENT_DATA_REQUEST'
const SET_CURRENT_DATA_SUCCESS = 'SET_CURRENT_DATA_SUCCESS'
const SET_CURRENT_DATA_FAILURE =  'SET_CURRENT_DATA_FAILURE'


export { 
  GET_POST_LIST_REQUEST, 
  GET_POST_LIST_SUCCESS, 
  GET_POST_LIST_FAILURE,
  FETCH_DELETE_POST_REQUEST,
  FETCH_DELETE_POST_SUCCESS,
  FETCH_DELETE_POST_FAILURE,
  SET_CURRENT_DATA_REQUEST,
  SET_CURRENT_DATA_SUCCESS,
  SET_CURRENT_DATA_FAILURE
}