const GET_POST_LIST_REQUEST = 'GET_POST_LIST_REQUEST'
const GET_POST_LIST_SUCCESS = 'GET_POST_LIST_SUCCESS'
const GET_POST_LIST_FAILURE = 'GET_POST_LIST_FAILURE' 

export { GET_POST_LIST_REQUEST, GET_POST_LIST_SUCCESS, GET_POST_LIST_FAILURE }